FROM ubuntu:24.04

RUN apt update
RUN apt install -y -- curl gcc libgc-dev libatomic-ops-dev libjansson-dev make file gdb git

RUN <<-EOF
        git clone https://github.com/jacketizer/libyuarel.git
        cd libyuarel
        make
        make install
EOF

RUN <<-EOF
        git clone https://github.com/zorgnax/libtap.git
        cd libtap
        make
        make install
        ldconfig
EOF

WORKDIR /mud/moosehead
COPY src src
COPY test test

WORKDIR /mud/moosehead/src
RUN make

WORKDIR /mud/moosehead/test
RUN make

ENTRYPOINT ["./test"]
