#! /bin/csh -f

# Change to area directory.
cd /app/area

# Set limits.
# limit stack 8192k
unlimit coredumpsize
umask 007
if ( -e shutdown.txt ) rm -f shutdown.txt
gzip -f /app/log/*.log

while ( 1 )
# Set up logfile name
    set index = 1000
    while ( 1 )
	set logfile = /app/log/$index.log
	if ( ! -e $logfile\.gz ) break
	@ index++
    end

    # Run moose.
    cd /app/src
    /app/src/moose 4000 >&! $logfile
    gzip $logfile

    # output debugging
    echo ''
    date
    if ( -e /app/src/moose.core ) then
    gdb -batch -x bt /app/src/moose /app/src/moose.core
    rm /app/src/moose.core
    else
	echo 'No core.'
    endif

    # Restart, giving old connections a chance to die.
    if ( -e /app/area/shutdown.txt ) then
	rm -f /app/area/shutdown.txt
	exit 0
    endif
    sleep 10
end
