name: CD - Build New Image

on:
  workflow_run:
    workflows: ["CI - Run Tests"]
    branches: [main]
    types: [completed]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/danielmunro/moosehead:${{ github.sha }}
