name: CI - Run Tests

on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - Dockerfile

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the tests
        run: ./bin/mhs test
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/danielmunro/moosehead:${{ github.sha }}
