name: CI - Run Tests

on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - Dockerfile

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run the tests
        run: ./bin/mhs test
