name: CI - Run Tests

on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - Dockerfile

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the tests
        run: ./bin/mhs test
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build and push a docker image
        run: ./bin/mhs prod_build ${{ github.repository_owner }} ${{ secrets.CR_PAT }} ghcr.io/danielmunro/moosehead:${{ github.sha }}
