name: CI - Run Tests

on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - Dockerfile

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build test docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: Dockerfile-test
          tags: test:latest
      - name: Run tests
        run: docker run test:latest
