on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - Dockerfile

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build test docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: Dockerfile-test
          tags: test:latest
      - name: Run tests
        run: docker run test:latest
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/danielmunro/moosehead:${{ github.sha }}
