name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The docker tag to deploy
        required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Get the key
        run: echo "${{ secrets.ID_RSA }}" > id_rsa
      - name: Deploy to production
        run: |
          ssh ${{ secrets.SSH_HOST }} -i id_rsa -p ${{ secrets.SSH_PORT }}
          cd ${{ secrets.CD_PATH }}
          mhs prod-deploy ${{ secrets.IMAGE_REPO }} ${{ inputs.tag }}
