name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The docker tag to deploy
        required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.ID_RSA }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - name: Deploy to production
        run: ./bin/mhs prod-deploy ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} ${{ secrets.SSH_PORT }} ${{ secrets.IMAGE_REPO }} ${{ inputs.tag }}
