name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The docker tag to deploy
        required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
      - name: Deploy to production
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }}
          cd ${{ secrets.CD_PATH }}
          mhs prod-deploy ${{ secrets.IMAGE_REPO }} ${{ inputs.tag }}
